
name: CI



on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install pytest flask-testing

      - run: pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:1.0.0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/flask-app:1.0.0'
          format: 'table'
          

      
